#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cJSON
Version  : 1.7.14
Release  : 1
URL      : https://github.com/DaveGamble/cJSON/archive/v1.7.14/cJSON-1.7.14.tar.gz
Source0  : https://github.com/DaveGamble/cJSON/archive/v1.7.14/cJSON-1.7.14.tar.gz
Summary  : An implementation of JSON Pointer, Patch and Merge Patch based on cJSON.
Group    : Development/Tools
License  : MIT
Requires: cJSON-lib = %{version}-%{release}
Requires: cJSON-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
# cJSON
Ultralightweight JSON parser in ANSI C.
## Table of contents
* [License](#license)
* [Usage](#usage)
* [Welcome to cJSON](#welcome-to-cjson)
* [Building](#building)
* [Copying the source](#copying-the-source)
* [CMake](#cmake)
* [Makefile](#makefile)
* [Vcpkg](#Vcpkg)
* [Including cJSON](#including-cjson)
* [Data Structure](#data-structure)
* [Working with the data structure](#working-with-the-data-structure)
* [Basic types](#basic-types)
* [Arrays](#arrays)
* [Objects](#objects)
* [Parsing JSON](#parsing-json)
* [Printing JSON](#printing-json)
* [Example](#example)
* [Printing](#printing)
* [Parsing](#parsing)
* [Caveats](#caveats)
* [Zero Character](#zero-character)
* [Character Encoding](#character-encoding)
* [C Standard](#c-standard)
* [Floating Point Numbers](#floating-point-numbers)
* [Deep Nesting Of Arrays And Objects](#deep-nesting-of-arrays-and-objects)
* [Thread Safety](#thread-safety)
* [Case Sensitivity](#case-sensitivity)
* [Duplicate Object Members](#duplicate-object-members)
* [Enjoy cJSON!](#enjoy-cjson)

%package dev
Summary: dev components for the cJSON package.
Group: Development
Requires: cJSON-lib = %{version}-%{release}
Provides: cJSON-devel = %{version}-%{release}
Requires: cJSON = %{version}-%{release}

%description dev
dev components for the cJSON package.


%package lib
Summary: lib components for the cJSON package.
Group: Libraries
Requires: cJSON-license = %{version}-%{release}

%description lib
lib components for the cJSON package.


%package license
Summary: license components for the cJSON package.
Group: Default

%description license
license components for the cJSON package.


%prep
%setup -q -n cJSON-1.7.14
cd %{_builddir}/cJSON-1.7.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1609864432
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1609864432
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cJSON
cp %{_builddir}/cJSON-1.7.14/LICENSE %{buildroot}/usr/share/package-licenses/cJSON/7953915bb3c653fd23ba9a96cbacabf2c005fad6
cp %{_builddir}/cJSON-1.7.14/tests/unity/docs/license.txt %{buildroot}/usr/share/package-licenses/cJSON/82d0bcdf2087a772a9517374e2df993d85fb447e
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/cjson/cJSON.h
/usr/lib64/cmake/cJSON/cJSONConfig.cmake
/usr/lib64/cmake/cJSON/cJSONConfigVersion.cmake
/usr/lib64/cmake/cJSON/cjson-relwithdebinfo.cmake
/usr/lib64/cmake/cJSON/cjson.cmake
/usr/lib64/libcjson.so
/usr/lib64/pkgconfig/libcjson.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libcjson.so.1
/usr/lib64/libcjson.so.1.7.14

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cJSON/7953915bb3c653fd23ba9a96cbacabf2c005fad6
/usr/share/package-licenses/cJSON/82d0bcdf2087a772a9517374e2df993d85fb447e
